---
- name: SSL certificate installed
  hosts: webservers
  pre_tasks:
    # https://github.com/geerlingguy/ansible-role-certbot/issues/21
    - name: Update apt
      ansible.builtin.apt:
        update_cache: true
  become: true
  vars:
    certbot_auto_renew_user: root
    certbot_create_if_missing: true
    certbot_admin_email: "{{ certbot_email }}"
    certbot_certs:
      - domains:
          - "{{ takahe_domain }}"
          - "{{ display_domain }}"
  roles:
    - geerlingguy.certbot
  tags:
    - ssl  # TODO: Find a better name?

- name: Install Docker and system dependencies
  hosts: webservers
  roles:
    - geerlingguy.docker
  tasks:
    - name: Install system dependencies
      ansible.builtin.package:
        name:
          - nginx
