---
- name: Clone the code from repository
  ansible.builtin.git:
    repo: "{{ takahe_repository }}"
    version: main
    dest: "{{ takahe_checkout_path }}"
  notify:
    - Restart Takahe

- name: Copy environment file
  ansible.builtin.template:
    src: takahe-envrc.j2
    dest: "{{ takahe_env_file }}"
    mode: u=r
  notify:
    - Restart Takahe

- name: Copy service definition
  ansible.builtin.template:
    src: takahe.service.j2
    dest: "{{ takahe_service_file }}"
    mode: u=rw,g=r,o=r
  notify:
    - Restart Takahe
